name: Bug report
about: Report a problem encountered in Talken core or client integrations.
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is and where you encountered it.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        - Operating system & version  
        - Runtime (Node.js / Rust / other) & version  
        - Transport in use (LAN, WiFi Direct, Bluetooth)  
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        List all steps needed to reproduce the issue, for example:
        1. Generate a new peer key pair  
        2. Start two nodes on a LAN  
        3. Send a message from A to B  
        4. Observe failure or error  
    validations:
      required: true

  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen.

  - type: textarea
    id: logs-or-screenshots
    attributes:
      label: Logs & error output
      description: Attach any relevant logs, stack traces, or screenshots here.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - blocker
        - critical
        - major
        - minor
        - trivial

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other information that might help diagnose the issue.
