name: "🐛 Bug Report"
description: "Report a reproducible bug or unexpected behavior in Talken."
title: "[BUG] "
labels:
  - bug
  - needs-triage
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please fill in the sections below.

  - type: input
    id: description
    attributes:
      label: "### Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "E.g. Sending a message to a peer crashes the app"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "List the precise steps to reproduce the behavior."
      placeholder: |
        1. Open Talken core example on two devices  
        2. Connect them over LAN  
        3. Send a message from Device A to Device B  
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: "Expected Behavior"
      placeholder: "What you expected to happen."

  - type: input
    id: actual
    attributes:
      label: "Actual Behavior"
      placeholder: "What actually happened."

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Please provide OS, Node/Rust version, hardware details, transport (WiFi/BLE) used, etc."
      placeholder: |
        - OS: Ubuntu 22.04  
        - Node.js v18.5.0  
        - Transport: LAN over personal hotspot  
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs / Error Messages"
      description: "Any logs, stack traces or error messages."
      placeholder: "Paste relevant console output here."

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      placeholder: "E.g. Occurs only when more than two peers are connected."
