name: "✨ Feature Request"
description: "Suggest a new feature or enhancement for Talken."
title: "[FEATURE] "
labels:
  - enhancement
  - needs-triage
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for thinking of ways to improve Talken! Please complete the template below.

  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "A one‑sentence summary of the requested feature."
      placeholder: "E.g. Add automatic peer reconnection on network drop"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this feature important? What use cases does it enable?"
      placeholder: "E.g. Improves reliability when peers frequently change networks"

  - type: textarea
    id: proposal
    attributes:
      label: "Proposed Solution"
      description: "Describe your idea for how Talken could implement this."
      placeholder: |
        - Introduce a reconnection monitor in transport layer  
        - On network change, attempt to re-discover existing peers  
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Other options you considered and why they were not chosen."
      placeholder: "E.g. Relying on application layer retries was too slow"

  - type: textarea
    id: impact
    attributes:
      label: "Impact"
      description: "Which modules or user flows will this affect?"
      placeholder: "E.g. transport module, peer management"

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Any extra information or screenshots/mockups."
      placeholder: "Sketch of UI change, links to libraries, etc."
